# Generated by Django 5.1.3 on 2024-11-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="accounts/profile_images/default_profile_image.png",
                        upload_to="accounts/profile_images",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profileimage",
            ),
        ),
    ]
