# Generated by Django 5.1.3 on 2024-11-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profileimage_user_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileimage",
            options={
                "verbose_name": "Profile Image",
                "verbose_name_plural": "Profile Images",
            },
        ),
    ]
