# Generated by Django 5.1.3 on 2024-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
