# Generated by Django 5.1.3 on 2024-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(unique=True),
        ),
    ]
